import os
import csv
import numpy as np
from collections import defaultdict


def load_results(path="serial_results.csv"):
    """
    Load cell measurement records from a CSV file.

    Args:
        path (str): Path to the CSV file generated by serial or parallel pipeline.

    Returns:
        list[dict]: List of cell measurement records.
    """
    records = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            records.append({
                "image": row["image"],
                "cell_id": int(row["cell_id"]),
                "area": float(row["area"]),
                "major_axis_length": float(row["major_axis_length"]),
                "minor_axis_length": float(row["minor_axis_length"]),
            })
    return records


def compute_summary(records):
    """
    Compute per-image summary statistics from cell measurement records.

    For each image, computes the number of detected cells, average and
    standard deviation of major axis length (length) and minor axis
    length (width). All measurements are in pixels.

    Args:
        records (list[dict]): List of cell measurement records.

    Returns:
        list[dict]: One summary record per image with the following fields:
            - image: filename
            - num_cells: number of detected cells
            - avg_major_axis: mean major axis length in pixels
            - std_major_axis: standard deviation of major axis length
            - avg_minor_axis: mean minor axis length in pixels
            - std_minor_axis: standard deviation of minor axis length
            - avg_area: mean cell area in pixels
    """
    # group records by image
    grouped = defaultdict(list)
    for record in records:
        grouped[record["image"]].append(record)

    summary = []
    for image, cells in sorted(grouped.items()):
        major = [c["major_axis_length"] for c in cells]
        minor = [c["minor_axis_length"] for c in cells]
        areas = [c["area"] for c in cells]

        summary.append({
            "image": image,
            "num_cells": len(cells),
            "avg_major_axis": round(float(np.mean(major)), 4),
            "std_major_axis": round(float(np.std(major)), 4),
            "avg_minor_axis": round(float(np.mean(minor)), 4),
            "std_minor_axis": round(float(np.std(minor)), 4),
            "avg_area": round(float(np.mean(areas)), 4),
        })

    return summary


def print_summary(summary):
    """
    Print per-image summary statistics to the console in a readable format.

    Args:
        summary (list[dict]): List of summary records from compute_summary.
    """
    header = f"{'Image':<30} {'Cells':>6} {'Avg Length':>12} {'Std Length':>12} {'Avg Width':>12} {'Std Width':>12} {'Avg Area':>10}"
    print(header)
    print("-" * len(header))

    for row in summary:
        print(
            f"{row['image']:<30} "
            f"{row['num_cells']:>6} "
            f"{row['avg_major_axis']:>12.2f} "
            f"{row['std_major_axis']:>12.2f} "
            f"{row['avg_minor_axis']:>12.2f} "
            f"{row['std_minor_axis']:>12.2f} "
            f"{row['avg_area']:>10.2f}"
        )


def save_summary(summary, path="summary_results.csv"):
    """
    Save per-image summary statistics to a CSV file.

    Args:
        summary (list[dict]): List of summary records.
        path (str): Output file path.
    """
    fieldnames = [
        "image", "num_cells", "avg_major_axis", "std_major_axis",
        "avg_minor_axis", "std_minor_axis", "avg_area"
    ]
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(summary)
    print(f"\nSummary saved to {path}")


if __name__ == "__main__":
    records = load_results("serial_results.csv")
    summary = compute_summary(records)
    print_summary(summary)
    save_summary(summary)